events {
  worker_connections 1024; # Default number of worker connections
}

http {
  # Prevent Nginx sync issues on OSX
  proxy_buffering off;

  # Include MIME types for proper content-type headers
  include /etc/nginx/mime.types;

  # HTTP server block to redirect to HTTPS
server {
    listen 80;
    server_name haske.online;

    # Let’s Encrypt challenge
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    # Redirect everything else to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}


  # HTTPS server block
  server {
    listen 5000 ssl http2; # Listen on port 5000 with SSL and HTTP/2
    server_name haske.online;

    # SSL Configuration
    ssl_certificate /etc/letsencrypt/live/haske.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/haske.online/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3; # Restrict to secure protocols
    ssl_ciphers HIGH:!aNULL:!MD5; # Use strong ciphers

    # Logging
    access_log logs/nginx-access.log;
    error_log logs/nginx-error.log;

    # Set maximum allowed size for client requests
    client_max_body_size 4G;

    # Define Orthanc backend
    set $orthanc 'http://50.17.224.101:8042';

    # Proxy settings for Orthanc endpoints
    location ~* ^/(patients|studies|instances|series|plugins|system|tools|statistics|modalities|dicom-web|osimis-viewer|ohif|stone-webviewer|peers|jobs|transfers|queries|auth|app|volview|changes|wsi) {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_pass $orthanc;
    }

    # Proxy settings for /ui/api/
    location /ui/api/ {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_pass $orthanc;
    }

    # Proxy settings for /ui/app/customizable/
    location /ui/app/customizable/ {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_pass $orthanc;
    }

    # Proxy settings for frontend development server
    location /ui/app/ {
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;
      rewrite /ui/app(.*) $1 break;
      proxy_pass https://127.0.0.1:3000;
    }

    # Default location for root path
    location / {
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;
      proxy_pass https://127.0.0.1:3000;
    }

    # Proxy settings for /orthanc/ path
    location /orthanc/ {
      proxy_pass $orthanc;
      rewrite /orthanc(.*) $1 break;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_request_buffering off;
      proxy_max_temp_file_size 0;
      client_max_body_size 0;
    }
  }
}
